title: "Machine Learning Build and Train Blog"
description: "A blog about building and training machine learning models."
url: "https://SSugumar2.github.io/Machine-Learning-Build-Train-Model"
theme: jekyll-theme-cayman
